/* libinputsynth-0.15.vapi generated by vapigen, do not modify. */

[CCode (cprefix = "libinputsynth", gir_namespace = "libinputsynth", gir_version = "0.15", lower_case_cprefix = "libinputsynth_")]
namespace libinputsynth {
}
