#!/bin/sh

set -e

action="$1"

if [ "$action" = configure ]; then
    update-alternatives --install /usr/bin/x-window-manager \
        x-window-manager /usr/bin/gala 50
fi


current_binding=$(gsettings get org.gnome.desktop.wm.keybindings show-desktop)

if [ ! -f /etc/gala-multitasking-keybinding-migration ]; then
    if [ "$current_binding" != "@as []" ]; then
        gsettings set io.elementary.desktop.wm.keybindings toggle-multitasking-view "$current_binding"
        gsettings set org.gnome.desktop.wm.keybindings show-desktop "@as []"
    fi
    touch /etc/gala-multitasking-keybinding-migration
fi

#DEBHELPER#
